# Generated by Django 2.1.3 on 2018-11-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=100)),
                ('film', models.CharField(max_length=100)),
                ('leading_actor', models.CharField(max_length=300)),
                ('year_release', models.DateField(blank=True, null=True, verbose_name='Cinematic Release')),
                ('oscars', models.SmallIntegerField(default=0)),
                ('imdb_link', models.URLField(max_length=100)),
                ('guardian_page', models.URLField(max_length=100)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='movie.Country')),
                ('director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='movie.Director')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='movie.Genre')),
            ],
        ),
    ]
