# Generated by Django 2.1.3 on 2018-11-24 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(default=236, on_delete=django.db.models.deletion.PROTECT, to='movie.Country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='entry',
            field=models.SmallIntegerField(default=0),
        ),
    ]
