# Generated by Django 2.1.3 on 2018-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20181124_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_release',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Cinematic Release'),
        ),
    ]
